#!/usr/bin/env bash
set -u

# Current directory
DIR="$(cd "$(dirname $0)" && pwd)/dotfiles"
cd "$DIR"

# Create symbolic links for each dotfile
link_dotfiles() {
  for file in $(find . -not -name '.DS_Store' | cut -c 3-); do
    local src="$DIR/$file"
    local dst="$HOME/$file"

    echo "Creating symlink: $src => $dst"
    local dir="$(dirname $file)"

    # create parent directory if it does not exist
    local parent_dir="$HOME/$dir"
    [[ ! -d "$parent_dir" ]] && mkdir -p "$parent_dir"

    ln -fs "$src" "$dst"
  done
}

main() {
  link_dotfiles
}

main