[tools]
node = "lts"
rust = "latest"
python = "3.11"

uv = "latest"
"cargo:pueue" = "latest"

awscli = { version = "latest", symlink_bins = "true" }
bats = "latest"
chezmoi = "latest"
dotenvx = "latest"
dust = "latest"
eza = "latest"
fd = "10.3" # for x86_64-apple-darwin
gcloud = "latest"
jq = "latest"
shellcheck = "latest"
shfmt = "latest"
terraform = "latest"
usage = "latest"
yazi = "latest"
yq = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:pnpm" = "latest"

"github:x-motemen/ghq" = "latest"
"github:d-kuro/gwq" = "latest"
"github:cli/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
